export type GlossaryCategory = 'estados-financieros' | 'valoracion' | 'ratios' | 'mercado' | 'conceptos-basicos';

export interface GlossaryTerm {
  term: string;
  termEn: string;
  definition: string;
  example: string;
  category: GlossaryCategory;
}

export const categoryLabels: Record<GlossaryCategory, string> = {
  'conceptos-basicos': 'Conceptos Básicos',
  'estados-financieros': 'Estados Financieros',
  'ratios': 'Ratios',
  'valoracion': 'Valoración',
  'mercado': 'Mercado',
};

export const glossaryTerms: GlossaryTerm[] = ([
  { term: "Acción", termEn: "Stock / Share", definition: "Unidad de propiedad en una empresa. Quien tiene acciones es dueño parcial de esa empresa y puede beneficiarse de su crecimiento.", example: "Si comprás 10 acciones de Apple, sos dueño de una pequeñísima parte de Apple.", category: "conceptos-basicos" },
  { term: "Activo", termEn: "Asset", definition: "Todo lo que una empresa posee y tiene valor económico. Incluye efectivo, propiedades, inventario y cuentas por cobrar.", example: "Las fábricas, el dinero en el banco y las patentes de Coca-Cola son sus activos.", category: "estados-financieros" },
  { term: "Amortización", termEn: "Amortization", definition: "Distribución del costo de un activo intangible a lo largo de su vida útil. Es similar a la depreciación pero para bienes no físicos.", example: "Si una empresa compra una patente por $100.000 que dura 10 años, amortiza $10.000 por año.", category: "estados-financieros" },
  { term: "Análisis Fundamental", termEn: "Fundamental Analysis", definition: "Método para evaluar el valor real de una empresa estudiando sus estados financieros, ventajas competitivas y perspectivas de crecimiento. Es lo que enseñamos en InvertíUY.", example: "Warren Buffett usa análisis fundamental para decidir si una empresa vale lo que cuesta en bolsa.", category: "conceptos-basicos" },
  { term: "Análisis Técnico", termEn: "Technical Analysis", definition: "Método que estudia gráficos de precios y patrones históricos para predecir movimientos futuros. No lo enseñamos en InvertíUY porque creemos en el análisis de los fundamentos del negocio.", example: "Un analista técnico mira líneas de tendencia y promedios móviles en un gráfico.", category: "conceptos-basicos" },
  { term: "Apalancamiento", termEn: "Leverage", definition: "Uso de deuda para financiar operaciones o inversiones. Puede amplificar tanto las ganancias como las pérdidas.", example: "Una empresa que usa mucha deuda para crecer está muy apalancada — si le va bien gana más, pero si le va mal el riesgo es mayor.", category: "ratios" },
  { term: "Balance General", termEn: "Balance Sheet", definition: "Estado financiero que muestra todo lo que una empresa tiene (activos), todo lo que debe (pasivos) y lo que queda para los dueños (patrimonio) en un momento dado.", example: "El balance de MercadoLibre muestra cuánto efectivo tiene, cuánta deuda debe y cuánto vale para sus accionistas.", category: "estados-financieros" },
  { term: "Beta", termEn: "Beta", definition: "Medida de cuánto se mueve el precio de una acción en relación al mercado general. Un beta mayor a 1 significa más volátil que el mercado.", example: "Una acción con beta 1.5 tiende a subir 15% cuando el mercado sube 10%, y caer 15% cuando baja 10%.", category: "mercado" },
  { term: "CAPEX", termEn: "Capital Expenditure", definition: "Dinero que una empresa gasta en comprar o mejorar activos a largo plazo como maquinaria, edificios o tecnología.", example: "Cuando Amazon construye un nuevo centro de distribución, ese gasto se registra como CAPEX.", category: "estados-financieros" },
  { term: "Capitalización Bursátil", termEn: "Market Cap", definition: "Valor total de mercado de una empresa, calculado multiplicando el precio de la acción por el número total de acciones en circulación.", example: "Si Apple tiene 15.000 millones de acciones a $190 cada una, su capitalización es de ~$2.85 billones.", category: "mercado" },
  { term: "DCF", termEn: "Discounted Cash Flow", definition: "Método de valoración que calcula cuánto vale una empresa hoy basándose en el dinero que se espera que genere en el futuro, ajustado por el valor del tiempo.", example: "Si una empresa va a generar $100 de flujo de caja por año durante 10 años, un DCF calcula cuánto vale eso hoy.", category: "valoracion" },
  { term: "Depreciación", termEn: "Depreciation", definition: "Reducción del valor contable de un activo físico a lo largo del tiempo por uso y desgaste. Aparece como gasto en el estado de resultados.", example: "Un camión que cuesta $50.000 y dura 10 años se deprecia $5.000 por año en los libros.", category: "estados-financieros" },
  { term: "Deuda", termEn: "Debt", definition: "Dinero que una empresa debe a terceros como bancos, bonistas u otros acreedores. Puede ser a corto plazo (menos de 1 año) o a largo plazo.", example: "Si una empresa pidió un préstamo de $1 millón al banco, eso es deuda.", category: "estados-financieros" },
  { term: "Diversificación", termEn: "Diversification", definition: "Estrategia de repartir las inversiones entre diferentes activos para reducir el riesgo. No poner todos los huevos en una canasta.", example: "En lugar de comprar solo acciones de una empresa, invertís en 20 empresas de distintos sectores y países.", category: "conceptos-basicos" },
  { term: "Dividendo", termEn: "Dividend", definition: "Porción de las ganancias que una empresa reparte en efectivo a sus accionistas, generalmente cada trimestre.", example: "Coca-Cola paga dividendos trimestrales — si tenés acciones, recibís plata cada 3 meses.", category: "conceptos-basicos" },
  { term: "EBITDA", termEn: "Earnings Before Interest, Taxes, Depreciation & Amortization", definition: "Indicador de rentabilidad operativa que muestra cuánto gana una empresa por su actividad principal, sin contar impuestos, deuda ni depreciación.", example: "Si una empresa tiene ingresos de $100M, costos operativos de $70M, su EBITDA es $30M.", category: "ratios" },
  { term: "EPS", termEn: "Earnings Per Share", definition: "Ganancia neta de la empresa dividida entre el número total de acciones. Indica cuánto gana la empresa por cada acción.", example: "Si una empresa gana $10 millones y tiene 5 millones de acciones, su EPS es $2.", category: "ratios" },
  { term: "Estado de Resultados", termEn: "Income Statement", definition: "Informe financiero que muestra los ingresos, costos y ganancias de una empresa durante un período. Te dice si la empresa ganó o perdió plata.", example: "El Income Statement de Netflix muestra cuánto cobró por suscripciones, cuánto gastó en contenido, y si le quedó ganancia.", category: "estados-financieros" },
  { term: "Flujo de Caja", termEn: "Cash Flow Statement", definition: "Estado financiero que muestra el movimiento real de efectivo: cuánto dinero entró y salió de la empresa en un período.", example: "Una empresa puede reportar ganancias pero tener flujo de caja negativo si sus clientes no le pagan a tiempo.", category: "estados-financieros" },
  { term: "Flujo de Caja Libre", termEn: "Free Cash Flow", definition: "Efectivo que genera una empresa después de cubrir todos sus gastos operativos e inversiones. Es el dinero 'libre' que queda para repartir o reinvertir.", example: "Si una empresa genera $50M de caja operativa y gasta $20M en CAPEX, su flujo de caja libre es $30M.", category: "estados-financieros" },
  { term: "Ganancia Neta", termEn: "Net Income", definition: "Lo que le queda a la empresa después de pagar absolutamente todo: costos, impuestos, intereses. Es la última línea del estado de resultados.", example: "Si una empresa factura $100M pero gasta $90M en total (costos, impuestos, etc.), su ganancia neta es $10M.", category: "estados-financieros" },
  { term: "Goodwill", termEn: "Goodwill", definition: "Activo intangible que aparece cuando una empresa compra a otra por más de lo que valen sus activos netos. Representa la marca, clientes y reputación.", example: "Si Facebook compró Instagram por $1.000M pero sus activos tangibles valían $100M, los $900M de diferencia son goodwill.", category: "estados-financieros" },
  { term: "Índice Bursátil", termEn: "Stock Index", definition: "Indicador que mide el rendimiento de un grupo de acciones representativas de un mercado. Sirve como termómetro general de la bolsa.", example: "El S&P 500 agrupa las 500 empresas más grandes de Estados Unidos y es el índice más seguido del mundo.", category: "mercado" },
  { term: "Ingresos", termEn: "Revenue", definition: "Todo el dinero que una empresa recibe por vender sus productos o servicios. Es la primera línea del estado de resultados.", example: "Si Nike vende zapatillas por $50.000 millones en un año, esos son sus ingresos.", category: "estados-financieros" },
  { term: "Liquidez", termEn: "Liquidity", definition: "Capacidad de una empresa para pagar sus deudas de corto plazo con lo que tiene disponible. También se refiere a lo fácil que es comprar o vender un activo.", example: "Una empresa con mucho efectivo tiene alta liquidez — puede pagar sus cuentas sin problemas.", category: "ratios" },
  { term: "Margen Bruto", termEn: "Gross Margin", definition: "Porcentaje de ingresos que queda después de restar el costo directo de producir lo que se vende. Indica cuán eficiente es la producción.", example: "Si vendés algo por $100 y te costó $40 hacerlo, tu margen bruto es 60%.", category: "ratios" },
  { term: "Margen Neto", termEn: "Net Margin", definition: "Porcentaje de ganancia neta sobre los ingresos totales. Indica cuánto gana realmente la empresa por cada peso que factura.", example: "Si una empresa factura $100 y su ganancia neta es $15, su margen neto es 15%.", category: "ratios" },
  { term: "Moat", termEn: "Economic Moat", definition: "Ventaja competitiva duradera que protege a una empresa de la competencia, como una marca fuerte, costos bajos o efectos de red. Concepto popularizado por Warren Buffett.", example: "Google tiene un moat enorme: su buscador es tan dominante que 'googlear' se convirtió en un verbo.", category: "valoracion" },
  { term: "Pasivo", termEn: "Liability", definition: "Todo lo que una empresa debe a terceros. Incluye préstamos, cuentas por pagar y obligaciones futuras.", example: "El salario que una empresa debe pagar el mes que viene es un pasivo.", category: "estados-financieros" },
  { term: "Patrimonio Neto", termEn: "Equity / Shareholders' Equity", definition: "Lo que queda para los dueños después de restar los pasivos de los activos. Representa el valor contable de la empresa para sus accionistas.", example: "Si una empresa tiene $500M en activos y $300M en deudas, su patrimonio neto es $200M.", category: "estados-financieros" },
  { term: "PEG Ratio", termEn: "Price/Earnings to Growth Ratio", definition: "Ratio que ajusta el P/E por la tasa de crecimiento esperada. Un PEG menor a 1 sugiere que la acción podría estar barata considerando su crecimiento.", example: "Si una empresa tiene P/E de 20 y crece al 20% anual, su PEG es 1.0 — valor justo según esta métrica.", category: "ratios" },
  { term: "Portafolio", termEn: "Portfolio", definition: "Conjunto de inversiones que posee una persona o institución. Un buen portafolio está diversificado para reducir el riesgo.", example: "Un portafolio simple podría tener 60% en acciones, 30% en bonos y 10% en efectivo.", category: "conceptos-basicos" },
  { term: "Ratio Precio/Ganancia", termEn: "P/E Ratio (Price-to-Earnings)", definition: "Relación entre el precio de la acción y las ganancias por acción. Indica cuántos años de ganancias estás pagando al comprar la acción.", example: "Si una acción cuesta $100 y la empresa gana $5 por acción, su P/E es 20 — estás pagando 20 años de ganancias.", category: "ratios" },
  { term: "Ratio Precio/Valor Libros", termEn: "P/B Ratio (Price-to-Book)", definition: "Relación entre el precio de mercado de la acción y su valor contable. Un P/B menor a 1 podría indicar que la empresa cotiza por debajo de su valor en libros.", example: "Si la acción vale $50 en el mercado pero el valor contable por acción es $25, su P/B es 2.", category: "ratios" },
  { term: "ROA", termEn: "Return on Assets", definition: "Rentabilidad sobre activos. Mide cuánta ganancia genera la empresa por cada peso de activos que posee. Indica eficiencia en el uso de recursos.", example: "Si una empresa tiene $100M en activos y gana $10M, su ROA es 10%.", category: "ratios" },
  { term: "ROE", termEn: "Return on Equity", definition: "Rentabilidad sobre el patrimonio. Mide cuánto gana la empresa por cada peso invertido por los accionistas. Uno de los ratios más importantes.", example: "Si el patrimonio es $50M y la ganancia neta es $10M, el ROE es 20% — un nivel excelente.", category: "ratios" },
  { term: "Solvencia", termEn: "Solvency", definition: "Capacidad de una empresa para cumplir con sus obligaciones a largo plazo. A diferencia de la liquidez, mira la salud financiera en el tiempo.", example: "Una empresa solvente puede pagar todas sus deudas a largo plazo sin problemas, incluso en años difíciles.", category: "ratios" },
  { term: "Tasa de Crecimiento", termEn: "Growth Rate", definition: "Velocidad a la que aumentan los ingresos, ganancias u otra métrica de una empresa de un período a otro, expresada como porcentaje.", example: "Si una empresa facturó $80M el año pasado y $100M este año, su tasa de crecimiento es 25%.", category: "valoracion" },
  { term: "Valor Intrínseco", termEn: "Intrinsic Value", definition: "Valor real o fundamental de una empresa según su capacidad de generar dinero, independiente de lo que diga el mercado. El objetivo del análisis fundamental es estimarlo.", example: "Si calculás que una empresa vale $50 por acción pero cotiza a $35, tiene un margen de seguridad del 30%.", category: "valoracion" },
  { term: "Value Investing", termEn: "Value Investing", definition: "Estrategia de inversión que busca comprar empresas por debajo de su valor intrínseco. Popularizada por Benjamin Graham y Warren Buffett.", example: "Un value investor compra acciones que el mercado subestima y espera pacientemente a que el precio refleje su valor real.", category: "conceptos-basicos" },
  { term: "Volatilidad", termEn: "Volatility", definition: "Medida de cuánto fluctúa el precio de un activo. Alta volatilidad significa que el precio sube y baja mucho en poco tiempo.", example: "Las acciones de empresas tecnológicas pequeñas suelen tener mayor volatilidad que las de empresas grandes y estables.", category: "mercado" },
  { term: "WACC", termEn: "Weighted Average Cost of Capital", definition: "Costo promedio que tiene una empresa para financiarse, considerando tanto deuda como capital propio. Se usa como tasa de descuento en el DCF.", example: "Si el WACC de una empresa es 10%, significa que necesita generar al menos 10% de retorno para crear valor.", category: "valoracion" },
  { term: "Working Capital", termEn: "Working Capital / Capital de Trabajo", definition: "Diferencia entre activos corrientes y pasivos corrientes. Indica si la empresa tiene recursos suficientes para operar día a día.", example: "Si una empresa tiene $30M en activos corrientes y $20M en pasivos corrientes, su working capital es $10M.", category: "estados-financieros" },
  { term: "Margen Operativo", termEn: "Operating Margin", definition: "Porcentaje de ingresos que queda después de cubrir los costos operativos (sin contar impuestos ni intereses). Muestra la eficiencia del negocio principal.", example: "Si una empresa factura $100M y su ganancia operativa es $25M, su margen operativo es 25%.", category: "ratios" },
  { term: "Rendimiento por Dividendo", termEn: "Dividend Yield", definition: "Porcentaje que representa el dividendo anual respecto al precio de la acción. Indica cuánto 'cobrarías' por año solo en dividendos.", example: "Si una acción cuesta $100 y paga $3 de dividendo al año, su rendimiento por dividendo es 3%.", category: "ratios" },
] as const).sort((a, b) => a.term.localeCompare(b.term, 'es')) as unknown as GlossaryTerm[];
