/**
 * StoneTrail - Foro Agora's educational journey symbol
 * 
 * Represents the path of growth and progress through financial education.
 * Built with intentional organic asymmetry (not mathematical precision).
 * Each stone has unique positioning, sizing, and spacing—reflecting natural variation.
 */

interface StoneTrailProps {
  className?: string;
}

const StoneTrail = ({ className = '' }: StoneTrailProps) => {
  // Each stone defined with explicit values (not generated by loops)
  // Intentional imperfections: varied x-offsets, sizes, and vertical spacing
  const stones = [
    // Bottom stone (foundation) - largest, serves as base
    {
      cx: 58,      // Slight left offset from center (120)
      cy: 280,
      rx: 52,      // Width radius
      ry: 24,      // Height radius
      animDelay: 0,
    },
    // Second stone - large, slight right shift
    {
      cx: 62,      // Right offset
      cy: 224,     // Closer spacing
      rx: 48,
      ry: 22,
      animDelay: 0.08,
    },
    // Middle stone - medium-large, back to left
    {
      cx: 57,      // Left again (asymmetry)
      cy: 166,     // Larger gap this time
      rx: 42,
      ry: 19,
      animDelay: 0.16,
    },
    // Third stone - medium, slight right
    {
      cx: 61,      // Right offset
      cy: 112,
      rx: 36,
      ry: 16,
      animDelay: 0.24,
    },
    // Small stone - upper third, left offset
    {
      cx: 55,      // Noticeably left
      cy: 62,      // Wider gap
      rx: 26,
      ry: 12,
      animDelay: 0.32,
    },
    // Top stone (peak) - smallest, centered
    {
      cx: 60,      // Center
      cy: 16,
      rx: 16,
      ry: 8,
      animDelay: 0.40,
    },
  ];

  return (
    <svg
      viewBox="0 0 120 296"
      xmlns="http://www.w3.org/2000/svg"
      className={`overflow-visible ${className}`}
      aria-hidden="true"
      role="presentation"
    >
      <defs>
        <style>
          {`
            @keyframes stone-fade-up {
              from {
                opacity: 0;
                transform: translateY(20px);
              }
              to {
                opacity: 1;
                transform: translateY(0);
              }
            }
            
            @keyframes stone-float {
              0%, 100% {
                transform: translateY(0px);
              }
              50% {
                transform: translateY(-8px);
              }
            }
            
            .stone {
              animation: stone-fade-up 0.8s cubic-bezier(0.34, 1.56, 0.64, 1) forwards,
                        stone-float 4s ease-in-out 1.2s infinite;
              opacity: 0;
            }
          `}
        </style>
      </defs>

      {stones.map((stone, index) => (
        <ellipse
          key={index}
          cx={stone.cx}
          cy={stone.cy}
          rx={stone.rx}
          ry={stone.ry}
          fill="#111111"
          className="stone"
          style={{
            animationDelay: `${stone.animDelay}s, ${stone.animDelay + 1.2}s`,
          }}
        />
      ))}
    </svg>
  );
};

export default StoneTrail;
